function u = uSolver(w,u,z,b,lambda,theta,omega,GSiter,debug)
    [n,m] = size(u);
    h = 1;
    D = ones(n,m);
    G = z;
	theta_dot_grad_w_b = theta*(Divergence(w,b)); 
    for iter=1:GSiter
        timer_counter = cputime;
        if debug == true
            disp(sprintf('inside loop:'));
        end
        u(1,1) = (1-omega)*u(1,1)+...
            omega*((lambda(1,1)*G(1,1)+(1/h^2)-theta_dot_grad_w_b(1,1))*(D(1,1)*(u(2,1)+u(1,2))))...
            /(lambda(1,1)+(1/h^2)*(2*D(1,1)));
        if n>2
            for i=2:n-1
                u(i,1) = (1-omega)*u(i,1)+...
                    omega*((lambda(i,1)*G(i,1)-theta_dot_grad_w_b(i,1))+(1/h^2)*(D(i,1)*(u(i+1,1)+u(i,2))+D(i-1,1)*u(i-1,1)))...
                    /(lambda(i,1)+(1/h^2)*(2*D(i,1)+D(i-1,1)));
            end
        end
        u(n,1) = (1-omega)*u(n,1)+...
            omega*((lambda(n,1)*G(n,1)-theta_dot_grad_w_b(n,1))+(1/h^2)*(D(n,1)*(u(n,2))+D(n-1,1)*u(n-1,1)))...
            /(lambda(n,1)+(1/h^2)*(D(n,1)+D(n-1,1)));
        if m>2
            for j=2:m-1
                u(1,j) = (1-omega)*u(1,j)+...
                    omega*((lambda(1,j)*G(1,j)-theta_dot_grad_w_b(1,j))+(1/h^2)*(D(1,j)*(u(2,j)+u(1,j+1))+D(1,j-1)*u(1,j-1)))...
                    /(lambda(1,j)+(1/h^2)*(2*D(1,j)+D(1,j-1)));
                for i=2:n-1    
                    u(i,j) = (1-omega)*u(i,j)+omega*((lambda(i,j)*G(i,j)-theta_dot_grad_w_b(i,j))+(1/h^2)*...
                        (D(i,j)*(u(i+1,j)+u(i,j+1))+D(i-1,j)*u(i-1,j)+D(i,j-1)*u(i,j-1)))/...
                        (lambda(i,j)+(1/h^2)*(2*D(i,j)+D(i-1,j)+D(i,j-1)));
                end
                u(n,j) = (1-omega)*u(n,j)+...
                    omega*((lambda(n,j)*G(n,j)-theta_dot_grad_w_b(n,j))+(1/h^2)*(D(n,j)*(u(n,j+1))+D(n-1,j)*u(n-1,j)+D(n,j-1)...
                    *u(n,j-1)))/(lambda(n,j)+(1/h^2)*(D(n,j)+D(n-1,j)+D(n,j-1)));
            end
        end
        u(1,m) = (1-omega)*u(1,m)+...
            omega*((lambda(1,m)*G(1,m)-theta_dot_grad_w_b(1,m))+(1/h^2)*(D(1,m)*(u(2,m))+D(1,m-1)...
            *u(1,m-1)))/(lambda(1,m)+(1/h^2)*(D(1,m)+D(1,m-1)));
        if n>2
            for i=2:n-1
                u(i,m) = (1-omega)*u(i,m)+...
                    omega*((lambda(i,m)*G(i,m)-theta_dot_grad_w_b(i,m))+(1/h^2)*(D(i,m)*(u(i+1,m))+D(i-1,m)*u(i-1,m)+D(i,m-1)...
                    *u(i,m-1)))/(lambda(i,m)+(1/h^2)*(D(i,m)+D(i-1,m)+D(i,m-1)));
            end
        end
        u(n,m) = (1-omega)*u(n,m)+...
            omega*((lambda(n,m)*G(n,m)-theta_dot_grad_w_b(n,m))+(1/h^2)*(D(n-1,m)*u(n-1,m)+D(n,m-1)...
            *u(n,m-1)))/(lambda(n,m)+(1/h^2)*(D(n-1,m)+D(n,m-1)));
        totaltime = cputime - timer_counter;
        if debug == true
            disp(sprintf('inside loop time: %f',totaltime));
        end
    end 
end